#!/usr/bin/env node

import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SETS_DIR = resolve(ROOT, 'vendor/xmage/Mage.Sets/src/mage/sets');
const CARDS_DIR = resolve(ROOT, 'vendor/xmage/Mage.Sets/src/mage/cards');
const OUT_FILE = resolve(ROOT, 'bridge/src/main/resources/card-index.txt');

const COMMANDER_FLAG = 'C';

const SUPER = /super\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*"([^"]+)"\s*,\s*(.*?),\s*SetType\.(\w+)/s;

const BUILD_DATE = /buildDate\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/;

const CARD =
  /new SetCardInfo\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*(?:"([^"]*)"|(\d+))\s*,\s*[^,]+,\s*mage\.cards\.\w+\.(\w+)\.class/g;

const TYPE_ARRAY = /new CardType\[]\s*\{([^}]*)}/g;
const SUPER_TYPE_ARRAY = /new SuperType\[]\s*\{([^}]*)}/g;
const SUB_TYPE_ARRAY = /new SubType\[]\s*\{([^}]*)}/g;

const ADDED_SUPER_TYPE = /this\.supertype\.add\(SuperType\.(\w+)\)/g;
const ADDED_SUB_TYPE = /this\.subtype\.add\(SubType\.(\w+)\)/g;

const CAN_BE_COMMANDER = /CanBeYourCommanderAbility/;

const PARTNER = /PartnerAbility\.getInstance\(\)/;

const PARTNER_WITH = /new PartnerWithAbility\(\s*"((?:[^"\\]|\\.)*)"/;

const PARTNER_VARIANT = /PartnerVariantType\.(\w+)\.makeAbility\(\)/g;

const CHOOSE_BACKGROUND = /ChooseABackgroundAbility\.getInstance\(\)/;

const DOCTORS_COMPANION = /DoctorsCompanionAbility\.getInstance\(\)/;

const STRING_LITERAL = /"((?:[^"\\]|\\.)*)"/g;

const BRACED = /\{([^{}]{1,5})}/g;

const COLORS = 'WUBRG';

const CONSTRUCTOR_MANA_COST =
  /super\(\s*ownerId\s*,\s*(?:setInfo|cardSetInfo)\s*,\s*(?:new \w+\[]\s*\{[^{}]*}\s*,\s*)+"((?:[^"\\]|\\.)*)"/;

const SET_TYPE_RANK = {
  EXPANSION: 0,
  CORE: 0,
  SUPPLEMENTAL_STANDARD_LEGAL: 0,
  SUPPLEMENTAL_MODERN_LEGAL: 0,
  SUPPLEMENTAL: 0,
  REMIX: 0,
  MAGIC_ONLINE: 1,
  MAGIC_ARENA: 1,
  PROMOTIONAL: 2,
  JOKE_SET: 3,
  CUSTOM_SET: 3,
};
const UNKNOWN_SET_TYPE_RANK = 2;

// Validation reuses the recorded date so future set releases do not invalidate an unchanged index.
const AS_OF = /^#.*\bas-of=(\d{8})\b/m;

async function main() {
  const check = process.argv.includes('--check');
  const existing = await readFile(OUT_FILE, 'utf8').then((text) => text.replaceAll('\r\n', '\n')).catch(() => null);
  const asOf = await asOfFrom(check ? existing : null);
  const sets = await readSets();
  const meta = await readCardMeta();
  const names = collectPrintings(sets, asOf, meta);

  const lines = [...names.keys()].sort((a, b) => a.localeCompare(b, 'en'));
  const printings = [...names.values()].reduce((sum, list) => sum + list.printings.length, 0);
  const eligible = [...names.values()].filter((card) => card.commander).length;

  const body = lines
    .map((name) => {
      const card = names.get(name);

      const letters = flagLettersOf(card);
      const extra = extraOf(card.partner);

      const flags = letters ? `\t${letters}\t${card.colors}${extra ? `\t${extra}` : ''}` : '';
      return `${name}\t${card.printings.map(keyOf).join(' ')}\t${card.category}\t${card.manaCost}${flags}`;
    })
    .join('\n');
  const file = `${header(sets.length, lines.length, printings, asOf)}${body}\n`;

  console.log(
    `${sets.length} sets, ${printings} printings, ${lines.length} distinct card names, ` +
      `${eligible} of them possible commanders (${(file.length / 1024 / 1024).toFixed(2)} MB)`,
  );

  if (check) {
    if (existing === file) {
      console.log('card-index.txt is up to date with the pinned submodule');
      return;
    }

    console.error(
      existing === null
        ? '\ncard-index.txt does not exist; run this without --check'
        : '\ncard-index.txt is STALE — the submodule has moved. Run this without --check.',
    );
    process.exit(1);
  }

  await writeFile(OUT_FILE, file);
  console.log(`wrote ${OUT_FILE.slice(ROOT.length + 1)}`);
}

function header(sets, names, printings, asOf) {
  return (
    '# XMage card index — GENERATED by tools/cards/build.mjs. Do not edit.\n' +
    '#\n' +
    '# Every card name in vendor/xmage/Mage.Sets, tab-separated from its printings as SET:NUMBER,\n' +
    '# in the order the bridge should prefer them (ordinary paper sets and newer printings first).\n' +
    '# Read by bridge CardIndex.kt to turn a pasted decklist into a .dck. Regenerate after a\n' +
    '# submodule bump; `--check` fails if this file no longer matches.\n' +
    '#\n' +
    `# sets=${sets} names=${names} printings=${printings} as-of=${asOf}\n`
  );
}

async function asOfFrom(existing) {
  const flag = process.argv.find((arg) => arg.startsWith('--as-of='))?.split('=')[1];
  if (flag) {
    const parsed = /^(\d{4})-(\d{2})-(\d{2})$/.exec(flag);
    if (!parsed) {
      console.error(`--as-of=${flag} is not a YYYY-MM-DD date`);
      process.exit(1);
    }
    return Number(parsed[1] + parsed[2] + parsed[3]);
  }
  const recorded = existing && AS_OF.exec(existing);
  if (recorded) return Number(recorded[1]);

  const now = new Date();
  return now.getFullYear() * 10000 + (now.getMonth() + 1) * 100 + now.getDate();
}

async function readSets() {
  const files = (await readdir(SETS_DIR).catch(() => null))?.filter((f) => f.endsWith('.java'));
  if (!files?.length) {
    console.error(`no set classes in ${SETS_DIR} — is the vendor/xmage submodule checked out?`);
    process.exit(1);
  }

  const sets = [];
  const unparsed = [];
  for (const file of files.sort()) {
    const source = await readFile(join(SETS_DIR, file), 'utf8');
    const superCall = SUPER.exec(source);
    if (!superCall) {
      unparsed.push(file);
      continue;
    }
    const [, , code, args, type] = superCall;
    const date = BUILD_DATE.exec(args);
    sets.push({
      code,
      type,

      released: date ? Number(date[1]) * 10000 + Number(date[2]) * 100 + Number(date[3]) : 0,
      source,
      file,
    });
  }

  if (unparsed.length) {
    console.warn(`${unparsed.length} set class(es) had no parsable super(...): ${unparsed.join(', ')}`);
  }
  return sets;
}

const UNFINISHED_LIST = /\bunfinished\s*=\s*Arrays\.asList\(([^)]*)\)/;
const REMOVE_UNFINISHED = /cards\.removeIf\(\s*setCardInfo\s*->\s*unfinished\.contains\(setCardInfo\.getName\(\)\)\s*\)/;

function unfinishedNames(source) {
  if (!REMOVE_UNFINISHED.test(source)) return new Set();
  const list = UNFINISHED_LIST.exec(source);
  if (!list) return new Set();
  return new Set([...list[1].matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => unescapeJava(m[1])));
}

function collectPrintings(sets, asOf, meta) {
  const names = new Map();
  for (const set of sets) {
    const unfinished = unfinishedNames(set.source);
    for (const match of set.source.matchAll(CARD)) {
      const name = unescapeJava(match[1]);
      if (unfinished.has(name)) continue;

      const number = match[2] ?? match[3];

      if (!names.has(name)) {
        const card = meta.get(match[4]);
        names.set(name, {
          printings: [],
          commander: card?.commander ?? false,
          colors: card?.colors ?? '',
          category: card?.category ?? OTHER_CATEGORY,
          manaCost: card?.manaCost ?? '',
          partner: card?.partner ?? EMPTY_PARTNER,
        });
      }
      names.get(name).printings.push({
        set: set.code,
        number,
        rank: rankOf(set),
        released: set.released,
        unreleased: set.released > asOf ? 1 : 0,
      });
    }
  }

  for (const card of names.values()) {
    const seen = new Set();
    card.printings = card.printings
      .sort(comparePrintings)

      .filter((printing) => !seen.has(keyOf(printing)) && seen.add(keyOf(printing)));
  }
  return names;
}

async function readCardMeta() {
  const eligible = new Map();
  let scanned = 0;

  for (const letter of await readdir(CARDS_DIR)) {
    const dir = join(CARDS_DIR, letter);
    const files = await readdir(dir).catch(() => null);
    if (!files) continue;

    for (const file of files) {
      if (!file.endsWith('.java')) continue;
      scanned++;
      const source = await readFile(join(dir, file), 'utf8');
      const commander = isCommander(source);
      const partner = partnerTagsOf(source);
      const anyFlag = commander || partner.partner || partner.partnerWith || partner.variants.length > 0 ||
        partner.chooseBackground || partner.isBackground || partner.doctorsCompanion || partner.isDoctor;
      eligible.set(file.slice(0, -'.java'.length), {
        commander,
        colors: anyFlag ? colorsOf(source) : '',
        category: categoryOf(source),
        manaCost: manaCostOf(source),
        partner,
      });
    }
  }

  if (!scanned) {
    console.error(`no card classes in ${CARDS_DIR} — is the vendor/xmage submodule checked out?`);
    process.exit(1);
  }
  const commanders = [...eligible.values()].filter((c) => c.commander).length;
  console.log(`cards: ${scanned} classes, ${commanders} may be a commander`);
  return eligible;
}

const EMPTY_PARTNER = {
  partner: false,
  partnerWith: '',
  variants: [],
  chooseBackground: false,
  isBackground: false,
  doctorsCompanion: false,
  isDoctor: false,
};

const OTHER_CATEGORY = 'O';
const CATEGORY_PRIORITY = [
  ['CREATURE', 'C'],
  ['PLANESWALKER', 'P'],
  ['BATTLE', 'B'],
  ['LAND', 'L'],
  ['INSTANT', 'I'],
  ['SORCERY', 'S'],
  ['ARTIFACT', 'A'],
  ['ENCHANTMENT', 'E'],
];

function categoryOf(source) {
  const types = declared(source, TYPE_ARRAY, /CardType\.(\w+)/g);
  for (const [type, letter] of CATEGORY_PRIORITY) if (types.has(type)) return letter;
  return OTHER_CATEGORY;
}

function colorsOf(source) {
  const found = new Set();
  for (const [, literal] of source.matchAll(STRING_LITERAL)) {
    for (const [, symbol] of literal.matchAll(BRACED)) {
      for (const letter of symbol) if (COLORS.includes(letter)) found.add(letter);
    }
  }
  return [...COLORS].filter((color) => found.has(color)).join('');
}

function manaCostOf(source) {
  return CONSTRUCTOR_MANA_COST.exec(source)?.[1] ?? '';
}

const PARTNER_FLAG = 'P';
const PARTNER_WITH_FLAG = 'W';
const PARTNER_VARIANT_FLAG = 'V';
const CHOOSE_BACKGROUND_FLAG = 'K';
const IS_BACKGROUND_FLAG = 'G';
const DOCTORS_COMPANION_FLAG = 'N';
const IS_DOCTOR_FLAG = 'T';

function flagLettersOf(card) {
  const p = card.partner;
  let letters = card.commander ? COMMANDER_FLAG : '';
  if (p.partner) letters += PARTNER_FLAG;
  if (p.partnerWith) letters += PARTNER_WITH_FLAG;
  if (p.variants.length > 0) letters += PARTNER_VARIANT_FLAG;
  if (p.chooseBackground) letters += CHOOSE_BACKGROUND_FLAG;
  if (p.isBackground) letters += IS_BACKGROUND_FLAG;
  if (p.doctorsCompanion) letters += DOCTORS_COMPANION_FLAG;
  if (p.isDoctor) letters += IS_DOCTOR_FLAG;
  return letters;
}

function extraOf(partner) {
  if (partner.partnerWith) return partner.partnerWith;
  if (partner.variants.length > 0) return partner.variants.join(',');
  return '';
}

function isCommander(source) {
  if (CAN_BE_COMMANDER.test(source)) return true;

  const superTypes = declared(source, SUPER_TYPE_ARRAY, /SuperType\.(\w+)/g, ADDED_SUPER_TYPE);
  if (!superTypes.has('LEGENDARY')) return false;

  const types = declared(source, TYPE_ARRAY, /CardType\.(\w+)/g);
  if (types.has('CREATURE')) return true;

  return declared(source, SUB_TYPE_ARRAY, /SubType\.(\w+)/g, ADDED_SUB_TYPE).has('VEHICLE');
}

function partnerTagsOf(source) {
  const subtypes = declared(source, SUB_TYPE_ARRAY, /SubType\.(\w+)/g, ADDED_SUB_TYPE);
  const partnerWith = PARTNER_WITH.exec(source);
  return {
    partner: PARTNER.test(source),
    partnerWith: partnerWith ? unescapeJava(partnerWith[1]) : '',
    variants: [...source.matchAll(PARTNER_VARIANT)].map((m) => m[1]),
    chooseBackground: CHOOSE_BACKGROUND.test(source),
    isBackground: subtypes.has('BACKGROUND'),
    doctorsCompanion: DOCTORS_COMPANION.test(source),
    isDoctor: subtypes.has('TIME_LORD') && subtypes.has('DOCTOR') && !subtypes.has('BRUSHWAGG'),
  };
}

function declared(source, arrayPattern, constantPattern, addPattern) {
  const found = new Set();
  for (const array of source.matchAll(arrayPattern)) {
    for (const constant of array[1].matchAll(constantPattern)) found.add(constant[1]);
  }
  if (addPattern) for (const added of source.matchAll(addPattern)) found.add(added[1]);
  return found;
}

function rankOf(set) {
  return SET_TYPE_RANK[set.type] ?? UNKNOWN_SET_TYPE_RANK;
}

function comparePrintings(a, b) {
  if (a.rank !== b.rank) return a.rank - b.rank;
  if (a.unreleased !== b.unreleased) return a.unreleased - b.unreleased;
  if (a.released !== b.released) return b.released - a.released;
  const plainA = /^\d+$/.test(a.number);
  const plainB = /^\d+$/.test(b.number);
  if (plainA !== plainB) return plainA ? -1 : 1;
  return a.number.localeCompare(b.number, 'en', { numeric: true });
}

function keyOf(printing) {
  return `${printing.set}:${printing.number}`;
}

function unescapeJava(text) {
  return text.replace(/\\(["'\\])/g, '$1');
}

await main();
